// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/14/2025, 8:08:23 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Tugas Akhir/PointMap/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/plugins/**/*.{js,ts,mjs}","D:/Tugas Akhir/PointMap/frontend/composables/**/*.{js,ts,mjs}","D:/Tugas Akhir/PointMap/frontend/utils/**/*.{js,ts,mjs}","D:/Tugas Akhir/PointMap/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Tugas Akhir/PointMap/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;